name: Developer answers

on:
  push:
    branches:
      - main

env:
  DOCKER_REGISTRY_USER: ${{ secrets.DOCKER_REGISTRY_USER }}
  DOCKER_REGISTRY_PASS: ${{ secrets.DOCKER_REGISTRY_PASS }}
  #

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code (GitHub action)
        uses: actions/checkout@v2
      - name: Setting COMMIT_ID env variable
        run: |
          echo "COMMIT_ID=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV
      - name: Build-n-push Devanswers Docker image
        run: |
          echo "Setting version"
          sed -i "s/COMMIT_ID/GitHub build $COMMIT_ID/g" templates/index.html
          echo "Login to Docker registry"
          docker login -u "${{ secrets.DOCKER_REGISTRY_LOGIN }}" -p "${{ secrets.DOCKER_REGISTRY_PASS }}"
          docker build . -t devanswers
          docker image tag devanswers:latest ${{ secrets.DOCKER_REGISTRY_USER }}/devanswers:latest
          docker image push ${{ secrets.DOCKER_REGISTRY_USER }}/devanswers:latest
          echo "Docker image ready."
